enabled: true

config_version: "1.0.1" # DON'T CHANGE THIS!

# SimpleWelcome V1.1.0
# Github: https://github.com/LuthMC
#
# You can see all available tags on wiki!
# https://github.com/LuthMC/SimpleWelcome/wiki/Available-Tags

messages:
  title: "§fWelcome, §b{name}!"
  subtitle: "§lExample Messages"
  auctionbar: "§l{online} Players | Your ping is {ping} ms."
  sound: "note.bell"  # Default sound

join_leave:
  enabled: true
  join_message: "§a{name} has joined the game"
  leave_message: "§c{name} has left the game"

teleport:
  enabled: false
  world: "world"
  x: 0
  y: 64
  z: 0
  
time:
  timezone: "Asia/Jakarta" # NOTE: use this https://php.net/manual/en/timezones.php
